### PR TITLE
Fix system image download location

### LINKED ISSUE #231: Uncaught Error: EACCES: permission denied, mkdir '/home/neothethird/testpool' (MainRenderer:90)
Automatically generated error report 
Version: 0.1.12-beta, snap build 105, available at the moment from the edge channel
Host OS: linux 
Host Dist: Ubuntu Linux 17.10
Package: Snap 
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/hymCCnQsHs/

### PR DESCRIPTION
**Pull request by NeoTheThird**
This together with https://github.com/ubports/system-image-node-module/pull/7 should fix #231.

### CODE REVIEW

**Comment by gsilvapt** [comment]
Hopefully it will provide some more insights to finally fix the Windows paths :smile:

**Comment by NeoTheThird** [comment]
It probably will. I guess what you have to do is look at the respective lines (some of which i just edited) in the system-image-module and make sure the ones that refer to the PC are normalized for the OS and the ones on the device are always normalized for unix.

**Comment by NeoTheThird** [comment]
Yep, you'll need to look there. I would assume that the file downloads correctly, just to the wrong location, or at least the location is provided incorrectly. The location path also comes from the system-image-module.

**Comment by NeoTheThird** [comment]
This is starting to get a little OT, so i'll just tag #110 here again. Anyways, if the problem is in the base path, that is generated "in-house": https://github.com/ubports/ubports-installer/blob/master/src/utils.js#L118

Anything else is probably the modules' fault.

**Comment by rdrowe** [comment]
Still broken guys - :-(

**Pull request merged**
