### PR TITLE
plugins: pmOS: allow passing in codename

### PR DESCRIPTION
**Pull request by amartinz**
Fallback to default config name, if not set.

This is for example needed for Fairphone 4 (FP4 vs fp4).

/cc @z3ntu

### CODE REVIEW

**Comment by amartinz** [comment]
Actually this way user gets a box presented with the codename in it and can modify it.
need to rethink this, sorry.

**Comment by z3ntu** [comment]
I'd do it like this (if it works)
```
  - name: "postmarketOS"
    codename: "fairphone-fp4"
    compatible_installer: ">=0.9.7-beta"
```
And this might be available in `this.props.os.codename` then?

**Comment by amartinz** [comment]
yes, i think that would be better.

To document my initial thoughts for the future, in case i forget.

https://github.com/ubports/ubports-installer/pull/2841

Which allows you to add additional settings for plugins very easily, like:

```
  - name: "postmarketOS"
    compatible_installer: ">=0.9.7-beta"
    options:
      - var: "codename"
        name: "Codename"
        type: "hidden"
        value: "axolotl"
      - var: "something_important"
        name: "Token or whatever?"
        type: "readonly"
        value: "shjafhjsagfjhasdf"
```

values would be obtainable like you see in this PR
`codename` is hidden and not shown at the dialog prompt.
`something_important` will be shown to user but not editable.

offers more flexibility for plugins but also makes it harder to validate.

but this is also way more verbose and not validated by the schema.

**Comment by amartinz** [comment]
> ```yaml
> codename: "fairphone-fp4"
> ```

This should now work, i have specified above within the `axolotl` config and it offerend me different options (`edge` only, while `axolotl` has `edge` and `v22.06`).

**Review by maciek134 — APPROVED** [review]

**Comment by z3ntu** [comment]
Seems to work great with https://github.com/ubports/installer-configs/pull/203, thank you!

**Pull request merged**
