### PR TITLE
add "Flash another!"-button

### PR DESCRIPTION
**Pull request by pajlow**
I created the button. :)

### CODE REVIEW

**Comment by NeoTheThird** [comment]
If you need me to help with that, just say the word :)

**Comment by pajlow** [comment]
Sorry for the late answer. Yes, a hint would be nice. I haven't worked with signals so far. Where should I call the function?

**Comment by NeoTheThird** [comment]
No problem, good to hear from you again :) Putting it in the `onclick` of the button together with the reload call should be fine. The function is `ipcRenderer.send()`, pass the [name of the signal](https://github.com/ubports/ubports-installer/blob/master/src/main.js#L50) as a first argument and an object that sets device and channel to undefined as a second. Alternatively, you could also define a new reset signal listener to reset those properties and call that. Your call :)

**Comment by NeoTheThird** [comment]
Awesome, that seems to work. Good job! All that's left to do is some design tweaks, maybe. Right now, the text on the last page is a little much with the additional button... Maybe put the get involved and donate buttons next to each other on a single line, that should do it.

Small tip (or maybe you have noticed already, don't know how experienced you are with electron): You can start the installer in debug mode by running it with `npm start -- --debug` and then run `views.show("done")` in the web console to immediately see the end-screen, so you know the results of your work without having to actually install :)

**Comment by pajlow** [comment]
Thank you! Is there an easy way to generate "returns" or empty elements in pug? Pug feels weird even when using the documentation.

**Comment by NeoTheThird** [comment]
Pug is just another syntax for html, so a line break would be `br`. Here's a converter, if it helps: https://html-to-pug.com/

**Comment by pajlow** [comment]
I still don't know about the button size and colour. Please tell me if u need further changes. ;)

**Pull request merged**
