### PR TITLE
Provide AppImage instructions without using the command line

### PR DESCRIPTION
**Pull request by probonopd**

### CODE REVIEW

**Comment by NeoTheThird** [comment]
Thanks :)

**Comment by probonopd** [comment]
Sorry, small typo, should be "Then run the file by double-clicking".

**Comment by NeoTheThird** [comment]
fixed

**Comment by NeoTheThird** [comment]
Is it possible that you didn't mean to link to https://github.com/AppImage/appimage.github.io/pull/44#partial-pull-merging but rather https://discourse.appimage.org/t/how-to-make-an-appimage-executable/80?

**Comment by probonopd** [comment]
You can bet! Thanks for catching and sorry for the confusion.

**Pull request merged**
