### PR TITLE
Adding desktop, desktop-legacy and wayland plugs

### PR DESCRIPTION
**Pull request by NeoTheThird**
Thanks to @jdstrand for the tip!

### CODE REVIEW

**Comment by mariogrip** [comment]
would we need wayland? electron does not run with wayland does it?

**Comment by NeoTheThird** [comment]
I can not provide a clear answer for that at the moment, i saw some news about it, but a quick search doesn't get me anything official. There's still [an open issue upstream](https://github.com/electron/electron/issues/10915), so let's put it on hold and leave it open for now.

**Comment by NeoTheThird** [comment]
@Flohack74 please don't create new labels

**Comment by Flohack74** [comment]
But he started it :D -
grafik

**Comment by NeoTheThird** [comment]
Bad @mariogrip, BAD!
sticker

We have issue tracking guidelines, let's use them please! https://docs.ubports.com/en/latest/about/process/issue-tracking.html

**Comment by Flohack74** [comment]
Well I must admit this is a pull request, and not an issue... I could imagine that such a label is useful for PRs.

**Comment by NeoTheThird** [comment]
No. You don't need it. Just request a change and github will block the merge. Using a new label is a dirty and ugly hack, and it will come up with the label for issues all the time as well. **Use reviews. Do not create labels.**

**Comment by NeoTheThird** [comment]
I think we can move forward with this as well.

**Pull request merged**
