### PR TITLE
Add workaround for fastboot flash async problem, addressing ubports#184

### PR DESCRIPTION
**Pull request by Ingo-FP-Angel**
Taken from gronkern's fork (c03d0faed7148da0920509e3b055fddaa41abdef)
and adapting code style.

Before merging I think it needs some confirmation by people actually using
the installer with this workaround applied.

### CODE REVIEW

**Comment by jonnius** [comment]
Did you consider the discussions going on in #330?

**Comment by Ingo-FP-Angel** [comment]
To be honest, I have ignored all parts about a general refactoring and concentrated on the last two comments of July 24th.

So, as nothing ever happened since 3 months my guess is that there is either a) some kind of deadlock where both NeoTheThird and gronkern are waiting for the other to open a PR with just the workaround (the only thing included here) or b) gronkern went AWOL.

In the meantime there were lots of reports by people having this "bootimage: incomplete or unsigned" error in the various UT telegram groups plus the UT and Fairphone forums. And I guess most of them were not able to test the workaround because there was no executable to try. I created and shared that in the Fairphone 2 and German UT telegram groups because that's where people asked for help. And here now is the PR where I hope to get things rolling again.

**Comment by jonnius** [comment]
I tried your test version. Unfortunately it does not work for me. I tried three times, each time getting a different error. One was simply `adb push error`, another `error: Devices: Error: could not find latest version; device: FP2 channel: ubports-touch/16.04/stable`.

**Comment by NeoTheThird** [comment]
Ok, it's building again. Anyone want to test? https://ci.ubports.com/job/ubports/job/ubports-installer/job/PR-517/6/artifact/dist/ubports-installer-0.1.21-beta-x86_64.AppImage

**Comment by NeoTheThird** [comment]
> Hard to say, the latter error occurs in code that downloads the files to flash, which hasn't been touched (and to me seems completely unrelated).

Well, it might be related. Since fastboot is executed synchronously now, it locks the gui thread and can lead to race conditions. So additional error handling might be in order.

Executing synchronously also causes some unresponsiveness for a couple of minutes when rebooting from one mode into another, the normal user will think the installer just died there... Wit these issues, i'd be reluctant to merge this, unless it completely and absolutely fixes the FP2 issues...

**Comment by elelel** [comment]
Hi, I've tested the image and it indeed gets past that error. However, after downloading the files from the internet and pushing them to /recovery/cache it fails at this point:
```
info: Rebooting to recovery to flash
debug: adb shell: echo 1
debug: Running platform tool exec cmd adb -P 5038 shell echo 1
debug: Running platform tool exec cmd adb -P 5038 shell stat -t /cache/recovery//ubports-9cae7daf84d964360d17e6b179c036b7533d6a6d00905a4b1c262e3632f7a01b.tar.xz.asc
debug: Running platform tool exec cmd adb -P 5038 shell stat -t /cache/recovery//device-60f53a5768e9340729d3a5ef9263bd3a9726792e7d0dbf830e5b124938dd419a.tar.xz
debug: Running platform tool exec cmd adb -P 5038 shell stat -t /cache/recovery//device-60f53a5768e9340729d3a5ef9263bd3a9726792e7d0dbf830e5b124938dd419a.tar.xz.asc
debug: Running platform tool exec cmd adb -P 5038 shell stat -t /cache/recovery//keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz
debug: Running platform tool exec cmd adb -P 5038 shell stat -t /cache/recovery//keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz.asc
debug:  message=Command failed: adb -P 5038 shell stat -t /cache/recovery//keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz
error: device '(null)' not found
, stack=Error: Command failed: adb -P 5038 shell stat -t /cache/recovery//keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz
error: device '(null)' not found

    at ChildProcess.exithandler (child_process.js:282:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12), killed=false, code=255, signal=null, cmd=adb -P 5038 shell stat -t /cache/recovery//keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz
debug:  message=Command failed: adb -P 5038 shell stat -t /cache/recovery//device-60f53a5768e9340729d3a5ef9263bd3a9726792e7d0dbf830e5b124938dd419a.tar.xz.asc

```

**Comment by Ingo-FP-Angel** [comment]
I think this has become obsolete with the work on 0.2.x

**Comment by NeoTheThird** [comment]
Yes. Sorry some of the effort you put into this was wasted, but i would have been reluctant to merge something that does not address the underlying issue and adds complexity to the already bloated installer. Granted, i did not understand the underlying issue either, when i reviewed this, but still. At least some parts of your work are now in the installer, like the convenience function for hiding the password. Thanks your work! :)

**Comment by Ingo-FP-Angel** [comment]
I don't mind at all. The core of it wasn't even my fix. It was a good use-case to actually start contributing and it nagged me the problem mostly seemed to affect the Fairphone 2 ;-)

**Pull request closed without merging**
