### PR TITLE
As per #184 and commented by @gronkern

### PR DESCRIPTION
**Pull request by gronkern**
Fix for the issue #184 (changed background processes to synchronous mode).
Added support for SSH_ASKPASS environment variable. (indices e7d984d..59d06e5 and b44cf4c..25bb249)

### CODE REVIEW

**Comment by NeoTheThird** [comment]
Thank you for your PR. Nevermind the CI status, electron-builder is currently broken.

For future PRs, *please* try and do multiple commits with meaningful commit messages, reviewing something like this is incredibly difficult and time consuming. I also made some small improvements to your code quality, i hope you don't mind. The whole codebase is pretty messy and really needs to be cleaned up, but if there is at least some form of a standard, it should be followed (eg spaces rather than tabs, no whitespace in empty lines, etc.).

There seems to be something wrong with some parts of the logic. I have only done three runs so far, but here's some issues i observed:

- If the device is selected manually, and the getprop signal is recieved later, the installer gets a huge hiccup and tries to go back to the chanel selection screen, while the installation is actually already running
- If there are no valid cached files, but the recovery still has a tarball it can install from (eg from a previous update), it will reboot and start installing from that while the files are still being downloaded. Not ideal.
- Transition between the downloading and pushing files to device screens seems to be wonky
- Password detection seems to be wonky

I will try and do more runs to see where exactly these issues lie. Or maybe you already have ideas? If so, don't hesitate to add commits.

Thanks!

**Comment by gronkern** [comment]
Hello @NeoTheThird I will try to improve the code quality. Do you have any style guides for some formatting tools available?
For the other issues I will to have a look at them in the next days. I am currently using a Linux System for the installing process.

**Comment by NeoTheThird** [comment]
No, we do not have a style guide, sorry. What I changed so far is basically just adopting the conventions that are obvious in all the files, like for example using spaces rather than tabs, and indentation widths. The rules are not set in stone anywhere (and there are many files that don't follow the conventions, which is something that needs to be fixed later on), but it's still possible to spot some general things.

**Comment by NeoTheThird** [comment]
Did you get somewhere? If you have questions, i'd be happy to help. By the way, the build is fixed on master now, so you might want to rebase for proper CI results and easier testing.

**Comment by gronkern** [comment]
Hi I did not get somewhere right now. But if I have time I will let you know.
Best regards

**Comment by NeoTheThird** [comment]
Fyi, i rebased the branch on master to get the CI unstuck.

**Comment by NeoTheThird** [comment]
Okay, that did not get Jenkins unstuck. Interesting, no idea why that is happening.

**Comment by NeoTheThird** [comment]
Hmm, I'm actually not so sure about this any more... I don't think it's a good idea to go synchronous. We might easily run into usability issues when locking the gui thread while waiting for the device, starting the adb service, etc. Sorry...

There's still some stuff we can cherry-pick from this, though! Askpass would be very nice to have, and you seem to have fixed #216 as well. Would you mind opening separate PRs for those?

**Comment by gronkern** [comment]
Hello,
I will open one. If you insist on asynchronous background processes another option would be to run shell scripts that sync with lock files or other mechanisms in the script. When I changed to synchronous background processes the issue disappeared. And the analysis showed that the adb processes were launched nearly simultaneously causing false results on flashing.
I also thought about an architectural approach for the issue. Imho it would be possible to have a "adb thread" that gets all commands from a pipe and synchronizes them. It could then contain all necessary information for the synchronization and error processing. This way the GUI and background processes would be isolated from each other and the queue could prevent thread synchronization issues between those two. What do you think about the idea?

**Comment by gronkern** [comment]
Hello,
as my last pull request as too complex and contained too much refactoring, I have developed a workaround for the issue. It basically just executes the fastboot flash processes synchronous. If you are interested please open another pull request for the issue.

**Comment by NeoTheThird** [comment]
Closing this. Since we do not need sud any more, we have no use for askpass where we're going. Thanks for your work, though! If you're interested to continue working on the installer, feel free to check out our help-wanted issues :)

**Pull request closed without merging**
